### ISSUE TITLE
Bazel 0.16 uses JDK9 to build, running a build on JDK 1.8 fails.

### ISSUE THREAD

**Issue by zhangyiwei** [google/gapid#2145]
I set the JAVA_HOME to the 1.8 JDK, and did a 'bazel shutdown', then I did a clean build. However I still got the below error when starting Gapid:
```
I20180815-125244895[main][server.ChildProcess.shutdown] Shutting down gapis
Uncaught exception in thread Thread[main,5,main]:
java.lang.NoSuchMethodError: java.nio.IntBuffer.flip()Ljava/nio/IntBuffer;
        at com.google.gapid.glcanvas.GlCanvas.chooseConfig(GlCanvas.java:134)
I20180815-125244895[server.ChildProcess-gapis][server.ChildProcess.runProcess] Killing gapis
        at com.google.gapid.glcanvas.GlCanvas.createContext(GlCanvas.java:98)
        at com.google.gapid.glcanvas.GlCanvas.<init>(GlCanvas.java:63)
        at com.google.gapid.widgets.ScenePanel.<init>(ScenePanel.java:52)
        at com.google.gapid.widgets.ImagePanel$ImageComponent.<init>(ImagePanel.java:758)
        at com.google.gapid.widgets.ImagePanel.lambda$new$0(ImagePanel.java:153)
        at com.google.gapid.widgets.LoadablePanel.<init>(LoadablePanel.java:56)
        at com.google.gapid.widgets.LoadablePanel.create(LoadablePanel.java:61)
        at com.google.gapid.widgets.ImagePanel.<init>(ImagePanel.java:152)
        at com.google.gapid.views.FramebufferView.<init>(FramebufferView.java:100)
        at com.google.gapid.MainWindow$MainTab.lambda$getTabs$5(MainWindow.java:544)
        at com.google.gapid.widgets.TabArea$Folder.addTab(TabArea.java:525)
        at com.google.gapid.widgets.TabArea$Folder.<init>(TabArea.java:509)
        at com.google.gapid.widgets.TabArea.<init>(TabArea.java:80)
        at com.google.gapid.MainWindow$4.createBottomControl(MainWindow.java:254)
        at com.google.gapid.widgets.FixedTopSplitter.<init>(FixedTopSplitter.java:39)
        at com.google.gapid.MainWindow$4.<init>(MainWindow.java:236)
        at com.google.gapid.MainWindow.createContents(MainWindow.java:236)
        at org.eclipse.jface.window.Window.create(Window.java:426)
        at org.eclipse.jface.window.Window.open(Window.java:783)
        at com.google.gapid.Main$UI.show(Main.java:118)
        at com.google.gapid.Main.main(Main.java:73)
W20180815-125244897[server.ChildProcess-gapis][server.ChildProcess.onExit] The gapis process exited with a non-zero exit value: -1
I20180815-125244897[server.ChildProcess-gapis][server.ChildProcess.shutdown] Shutting down gapis
I20180815-125244911[OkHttpClientTransport][io.grpc.internal.ManagedChannelImpl.maybeTerminateChannel] [ManagedChannelImpl@3ca5cd99] Terminated
```

**Comment by zhangyiwei** [comment]
I'm doubting if it's because the binaries of jdk9 lives in my $PATH even though I set $JAVA_HOME to jdk8. Will try again using a clean $PATH

**Comment by zhangyiwei** [comment]
It still doesn't work even if I build with a clean $PATH.

**Comment by Qining** [comment]
Same issue here @pmuetschard

**Comment by Qining** [comment]
@zhangyiwei I changed my java and javac in my PATH to jdk9 (java -version returns version 9) and now I can have the GUI started correctly.

**Comment by pmuetschard** [comment]
Starting with bazel 0.16, it defaults to building with the bazel-shipped-jdk9. So it doesn't actually matter what version you have installed. Will fix.

https://blog.bazel.build/2018/07/31/bazel-0.16.html
