### ISSUE TITLE
Linux build fails

### ISSUE THREAD

**Issue by Wyverex42** [google/gapid#635]
The current build (6601f870a2bfa62f5683dda4972a292898236702) fails on Ubuntu 17.04. Installation was carried out as described in the instructions.

```akruegersen@HA-366K:~/go/src/github.com/google/gapid$ ./do build
Major changes made to CMake. Forcing a full rebuild.
-- Building GAPID 0.4.0:0:developer
-- Found aarch64 using /home/akruegersen/keen_blobs/platform/android/android-ndk-r12b/linux_x64/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-gcc
-- Found armeabi using /home/akruegersen/keen_blobs/platform/android/android-ndk-r12b/linux_x64/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc
-- Found x86 using /home/akruegersen/keen_blobs/platform/android/android-ndk-r12b/linux_x64/toolchains/x86-4.9/prebuilt/linux-x86_64/bin/i686-linux-android-gcc
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Setting install path to /home/akruegersen/apps/gapid/release/pkg
-- Initial dependancies for cmd-apic
-- Initial dependancies for core-app
-- Initial dependancies for core-app-flags
-- Initial dependancies for core-assert
-- Initial dependancies for core-data-compare
-- Initial dependancies for core-log
-- Initial dependancies for core-context-keys
-- Initial dependancies for core-text
-- Initial dependancies for core-math-sint
-- Initial dependancies for core-fault
-- Initial dependancies for core-event-task
-- Initial dependancies for core-os-file
-- Initial dependancies for core-text-parse
-- Initial dependancies for core-text-parse-test
-- Initial dependancies for gapil
-- Initial dependancies for gapil-ast
-- Initial dependancies for gapil-parser
-- Initial dependancies for gapil-resolver
-- Initial dependancies for gapil-semantic
-- Initial dependancies for core-data-slice
-- Initial dependancies for gapil-semantic-printer
-- Initial dependancies for core-text-reflow
-- Initial dependancies for gapil-format
-- Initial dependancies for gapil-template
-- Initial dependancies for core-os-shell
-- Initial dependancies for core-text-copyright
-- Initial dependancies for gapil-analysis
-- Initial dependancies for core-math-interval
-- Initial dependancies for core-math-u64
-- Initial dependancies for gapil-constset
-- Initial dependancies for gapil-validate
-- Initial dependancies for cmd-clean_generated
-- Initial dependancies for cmd-copyright
-- Initial dependancies for cmd-dump-manifest
-- Initial dependancies for core-os-android-apk
-- Initial dependancies for core-os-android-binaryxml
-- Initial dependancies for core-data-binary
-- Initial dependancies for core-math-f16
-- Initial dependancies for core-math-u32
-- Initial dependancies for core-data-endian
-- Initial dependancies for core-os-device
-- Initial dependancies for core-data-id
-- Initial dependancies for core-os-device-host
-- Initial dependancies for core-data-binary-test
-- Initial dependancies for core-os-android-manifest
-- Initial dependancies for cmd-embed
-- Initial dependancies for cmd-filehash
-- Initial dependancies for cmd-font-gen
-- Initial dependancies for cmd-gapis
-- Initial dependancies for core-app-auth
-- Initial dependancies for core-os-android-adb
-- Initial dependancies for core-os-android
-- Initial dependancies for core-os-device-bind
-- Initial dependancies for core-os-shell-stub
-- Initial dependancies for gapir-client
-- Initial dependancies for core-app-layout
-- Initial dependancies for core-os-process
-- Initial dependancies for core-vulkan-loader
-- Initial dependancies for gapidapk
-- Initial dependancies for gapidapk-pkginfo
-- Initial dependancies for gapis-replay-protocol
-- Initial dependancies for core-data-pod
-- Initial dependancies for gapis-database
-- Initial dependancies for core-data-protoconv
-- Initial dependancies for gapis-config
-- Initial dependancies for gapis-replay
-- Initial dependancies for core-app-benchmark
-- Initial dependancies for core-image
-- Initial dependancies for core-data-protoutil
-- Initial dependancies for core-stream
-- Initial dependancies for core-math-f32
-- Initial dependancies for core-math-f64
-- Initial dependancies for core-stream-fmts
-- Initial dependancies for core-image-astc
-- Initial dependancies for gapis-atom
-- Initial dependancies for core-data-deep
-- Initial dependancies for core-data
-- Initial dependancies for gapis-atom-atom_pb
-- Initial dependancies for gapis-gfxapi
-- Initial dependancies for gapis-memory
-- Initial dependancies for gapis-replay-value
-- Initial dependancies for gapis-service-box
-- Initial dependancies for gapis-service-path
-- Initial dependancies for gapis-vertex
-- Initial dependancies for gapis-stringtable
-- Initial dependancies for gapis-memory-memory_pb
-- Initial dependancies for gapis-replay-builder
-- Initial dependancies for gapis-replay-asm
-- Initial dependancies for gapis-replay-opcode
-- Initial dependancies for gapis-service
-- Initial dependancies for core-log-log_pb
-- Initial dependancies for gapis-atom-test
-- Initial dependancies for gapis-atom-test-test_pb
-- Initial dependancies for gapis-atom-transform
-- Initial dependancies for gapis-capture
-- Initial dependancies for core-data-pack
-- Initial dependancies for gapis-replay-executor
-- Initial dependancies for gapis-replay-scheduler
-- Initial dependancies for gapis-server
-- Initial dependancies for core-net-grpcutil
-- Initial dependancies for core-event
-- Initial dependancies for gapis-gfxapi-all
-- Initial dependancies for gapis-gfxapi-core
-- Initial dependancies for gapis-gfxapi-core-core_pb
-- Initial dependancies for gapis-gfxapi-gles
-- Initial dependancies for gapis-gfxapi-gles-gles_pb
-- Initial dependancies for gapis-gfxapi-gles-glsl
-- Initial dependancies for gapis-gfxapi-gles-glsl-ast
-- Initial dependancies for gapis-gfxapi-gles-glsl-evaluator
-- Initial dependancies for gapis-gfxapi-gles-glsl-parser
-- Initial dependancies for gapis-gfxapi-gles-glsl-builtins
-- Initial dependancies for gapis-gfxapi-gles-glsl-preprocessor
-- Initial dependancies for gapis-gfxapi-gles-glsl-sema
-- Initial dependancies for gapis-messages
-- Initial dependancies for gapis-resolve
-- Initial dependancies for gapis-replay-devices
-- Initial dependancies for gapis-shadertools
-- Initial dependancies for gapis-gfxapi-vulkan
-- Initial dependancies for gapis-gfxapi-vulkan-vulkan_pb
-- Initial dependancies for cmd-gapit
-- Initial dependancies for core-image-font
-- Initial dependancies for core-video
-- Initial dependancies for gapii-client
-- Initial dependancies for core-java-jdbg
-- Initial dependancies for core-java-jdwp
-- Initial dependancies for core-java-jdwp-test
-- Initial dependancies for gapis-client
-- Initial dependancies for cmd-gopherjs
-- Initial dependancies for cmd-lingo
-- Initial dependancies for test-robot-lingo-generator
-- Initial dependancies for cmd-make-debuggable
-- Initial dependancies for cmd-perf
-- Initial dependancies for cmd-protoc-gen-go
-- Initial dependancies for cmd-pullapk
-- Initial dependancies for cmd-robot
-- Initial dependancies for core-git
-- Initial dependancies for test-robot-build
-- Initial dependancies for test-robot-record
-- Initial dependancies for test-robot-search
-- Initial dependancies for test-robot-search-eval
-- Initial dependancies for test-robot-stash
-- Initial dependancies for test-robot-job
-- Initial dependancies for test-robot-master
-- Initial dependancies for test-robot-monitor
-- Initial dependancies for test-robot-job-worker
-- Initial dependancies for test-robot-replay
-- Initial dependancies for test-robot-report
-- Initial dependancies for test-robot-subject
-- Initial dependancies for test-robot-trace
-- Initial dependancies for test-robot-scheduler
-- Initial dependancies for test-robot-search-script
-- Initial dependancies for test-robot-lingo
-- Initial dependancies for test-robot-search-query
-- Initial dependancies for test-robot-stash-grpc
-- Initial dependancies for test-robot-stash-local
-- Initial dependancies for test-robot-web
-- Initial dependancies for cmd-shadertool
-- Initial dependancies for cmd-stash
-- Initial dependancies for cmd-stringgen
-- Initial dependancies for gapis-stringtable-parser
-- Initial dependancies for gapis-stringtable-minidown
-- Initial dependancies for gapis-stringtable-minidown-node
-- Initial dependancies for gapis-stringtable-minidown-parser
-- Initial dependancies for gapis-stringtable-minidown-scanner
-- Initial dependancies for gapis-stringtable-minidown-token
-- Initial dependancies for cmd-verify_gles_api
-- Found DLOpen: /usr/lib/x86_64-linux-gnu/libdl.so  
-- Found PThread: /usr/lib/x86_64-linux-gnu/libpthread.so  
-- Found RT: /usr/lib/x86_64-linux-gnu/librt.so  
-- Found X11: /usr/lib/x86_64-linux-gnu/libX11.so  
-- Found GL: /usr/lib/x86_64-linux-gnu/libGL.so  
-- Initial dependancies for gapil-langsvr
-- Initial dependancies for core-langsvr
-- Initial dependancies for core-langsvr-protocol
-- Initial dependancies for gapis-gfxapi-test
-- Initial dependancies for gapis-gfxapi-test-gfxapi_test_import
-- Initial dependancies for gapis-gfxapi-test-test_pb
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Initial dependancies for test-integration-replay-gles-samples
-- Initial dependancies for test-integration-replay-gles
-- Initial dependancies for test-integration-replay
-- Initial dependancies for test-integration-service
-- Initial dependancies for test-robot-lingo-examples-calc
-- Initial dependancies for test-robot-lingo-examples-cstcalc
-- Initial dependancies for test-robot-lingo-examples-simplecalc
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    MSYS2_PATH


-- Build files have been written to: /home/akruegersen/apps/gapid/release
[213/364] Embed generating /home/akruegersen/go/src/github.com/google/gapid/cmd/stringgen/stringgen_embed.go
16:07:36.485 I: <embed> Embed stringdefgo_tmpl from /home/akruegersen/go/src/github.com/google/gapid/cmd/stringgen/stringdefgo.tmpl

16:07:36.485 I: <embed> Embed stringdefapi_tmpl from /home/akruegersen/go/src/github.com/google/gapid/cmd/stringgen/stringdefapi.tmpl

[217/364] Embed generating /home/akruegersen/go/src/github.com/google/gapid/test/robot/web/web_embed.go
16:07:36.569 I: <embed> Embed components_js from /home/akruegersen/go/src/github.com/google/gapid/test/robot/web/www/components/components.js

16:07:36.569 I: <embed> Embed gapid_artifacts_html from /home/akruegersen/go/src/github.com/google/gapid/test/robot/web/www/components/gapid-artifacts.html

16:07:36.569 I: <embed> Embed gapid_artifacts_js from /home/akruegersen/go/src/github.com/google/gapid/test/robot/web/www/components/gapid-artifacts.js

16:07:36.569 I: <embed> Embed gapid_packages_html from /home/akruegersen/go/src/github.com/google/gapid/test/robot/web/www/components/gapid-packages.html

16:07:36.569 I: <embed> Embed gapid_packages_js from /home/akruegersen/go/src/github.com/google/gapid/test/robot/web/www/components/gapid-packages.js

16:07:36.569 I: <embed> Embed gapid_satellites_html from /home/akruegersen/go/src/github.com/google/gapid/test/robot/web/www/components/gapid-satellites.html

16:07:36.569 I: <embed> Embed gapid_satellites_js from /home/akruegersen/go/src/github.com/google/gapid/test/robot/web/www/components/gapid-satellites.js

16:07:36.569 I: <embed> Embed gapid_subjects_html from /home/akruegersen/go/src/github.com/google/gapid/test/robot/web/www/components/gapid-subjects.html

16:07:36.569 I: <embed> Embed gapid_subjects_js from /home/akruegersen/go/src/github.com/google/gapid/test/robot/web/www/components/gapid-subjects.js

16:07:36.569 I: <embed> Embed gapid_tracks_html from /home/akruegersen/go/src/github.com/google/gapid/test/robot/web/www/components/gapid-tracks.html

16:07:36.569 I: <embed> Embed gapid_tracks_js from /home/akruegersen/go/src/github.com/google/gapid/test/robot/web/www/components/gapid-tracks.js

16:07:36.569 I: <embed> Embed gapid_workers_html from /home/akruegersen/go/src/github.com/google/gapid/test/robot/web/www/components/gapid-workers.html

16:07:36.569 I: <embed> Embed gapid_workers_js from /home/akruegersen/go/src/github.com/google/gapid/test/robot/web/www/components/gapid-workers.js

16:07:36.569 I: <embed> Embed styles_css from /home/akruegersen/go/src/github.com/google/gapid/test/robot/web/www/css/styles.css

16:07:36.569 I: <embed> Embed directives_js from /home/akruegersen/go/src/github.com/google/gapid/test/robot/web/www/directives/directives.js

16:07:36.569 I: <embed> Embed favicon_png from /home/akruegersen/go/src/github.com/google/gapid/test/robot/web/www/favicon.png

16:07:36.569 I: <embed> Embed grid_html from /home/akruegersen/go/src/github.com/google/gapid/test/robot/web/www/grid.html

16:07:36.679 I: <embed> Embed grid_js from /home/akruegersen/go/src/github.com/google/gapid/test/robot/web/www/grid/grid.js

16:07:36.679 I: <embed> Embed android_png from /home/akruegersen/go/src/github.com/google/gapid/test/robot/web/www/images/os/android.png

16:07:36.683 I: <embed> Embed linux_png from /home/akruegersen/go/src/github.com/google/gapid/test/robot/web/www/images/os/linux.png

16:07:36.683 I: <embed> Embed osx_png from /home/akruegersen/go/src/github.com/google/gapid/test/robot/web/www/images/os/osx.png

16:07:36.683 I: <embed> Embed windows_png from /home/akruegersen/go/src/github.com/google/gapid/test/robot/web/www/images/os/windows.png

16:07:36.683 I: <embed> Embed index_html from /home/akruegersen/go/src/github.com/google/gapid/test/robot/web/www/index.html

16:07:36.683 I: <embed> Embed gapid_selection_js from /home/akruegersen/go/src/github.com/google/gapid/test/robot/web/www/services/gapid-selection.js

16:07:36.683 I: <embed> Embed services_js from /home/akruegersen/go/src/github.com/google/gapid/test/robot/web/www/services/services.js

[245/364] protoc
github.com/google/gapid/gapis/gfxapi/gfxapi.proto: warning: Import core/data/pod/pod.proto but not used.
[266/364] protoc
gapis/gfxapi/gfxapi.proto: warning: Import core/data/pod/pod.proto but not used.
[276/364] protoc
gapis/gfxapi/gfxapi.proto: warning: Import core/data/pod/pod.proto but not used.
[307/364] stringgen using /home/akruegersen/go/src/github.com/google/gapid/gapis/messages/en-us.stb.md
16:07:43.989 I: <stringgen> Found 1 string table file(s)
[312/364] protoc
github.com/google/gapid/gapis/gfxapi/core/core_pb/api.proto: warning: Import gapis/memory/memory_pb/memory.proto but not used.
[313/364] protoc
gapis/gfxapi/core/core_pb/api.proto: warning: Import gapis/memory/memory_pb/memory.proto but not used.
[364/364] Apic on /home/akruegersen/go/src/github.com/google/gapid/gapis/gfxapi/gles/gles.api with cc_gles_api_spy.cpp.tmpl
[0/1] Re-running CMake...
-- Building GAPID 0.4.0:0:developer
-- Configuring done
-- Generating done
-- Build files have been written to: /home/akruegersen/apps/gapid/release
[6/561] Building CXX object CMakeFiles/astc-encoder.dir/third_party/astc-encoder/Source/softfloat.cpp.o
FAILED: CMakeFiles/astc-encoder.dir/third_party/astc-encoder/Source/softfloat.cpp.o 
/usr/bin/c++   -DTARGET_OS_LINUX -I/home/akruegersen/go/src/github.com/google/gapid -I/home/akruegersen/go/src/github.com/google/gapid/third_party/SPIRV-Headers/include -I/home/akruegersen/go/src/github.com/google/gapid/third_party/SPIRV-Tools/include -I/home/akruegersen/go/src/github.com/google/gapid/third_party/SPIRV-Tools/source -I/home/akruegersen/go/src/github.com/google/gapid/third_party/SPIRV-Tools-Generated -I/home/akruegersen/go/src/github.com/google/gapid/third_party/glslang/OGLCompilersDLL -I/home/akruegersen/go/src/github.com/google/gapid/core/memory_tracker/cc -I/home/akruegersen/go/src/github.com/google/gapid/core/vulkan/cc/include -std=c++0x -O3 -DNDEBUG -fPIC   -DGAPID_VERSION_AND_BUILD=\"0.4.0:0:developer\" -Wno-c++11-narrowing -MD -MT CMakeFiles/astc-encoder.dir/third_party/astc-encoder/Source/softfloat.cpp.o -MF CMakeFiles/astc-encoder.dir/third_party/astc-encoder/Source/softfloat.cpp.o.d -o CMakeFiles/astc-encoder.dir/third_party/astc-encoder/Source/softfloat.cpp.o -c /home/akruegersen/go/src/github.com/google/gapid/third_party/astc-encoder/Source/softfloat.cpp
/home/akruegersen/go/src/github.com/google/gapid/third_party/astc-encoder/Source/softfloat.cpp: In function ‘sf32 sf16_to_sf32(sf16)’:
/home/akruegersen/go/src/github.com/google/gapid/third_party/astc-encoder/Source/softfloat.cpp:142:2: error: narrowing conversion of ‘2147483648u’ from ‘unsigned int’ to ‘int32_t {aka int}’ inside { } [-Wnarrowing]
  };
  ^
/home/akruegersen/go/src/github.com/google/gapid/third_party/astc-encoder/Source/softfloat.cpp:142:2: error: narrowing conversion of ‘2147713024u’ from ‘unsigned int’ to ‘int32_t {aka int}’ inside { } [-Wnarrowing]
/home/akruegersen/go/src/github.com/google/gapid/third_party/astc-encoder/Source/softfloat.cpp:142:2: error: narrowing conversion of ‘2147713024u’ from ‘unsigned int’ to ‘int32_t {aka int}’ inside { } [-Wnarrowing]
/home/akruegersen/go/src/github.com/google/gapid/third_party/astc-encoder/Source/softfloat.cpp:142:2: error: narrowing conversion of ‘2147942400u’ from ‘unsigned int’ to ‘int32_t {aka int}’ inside { } [-Wnarrowing]
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-c++11-narrowing’
[7/561] Building CXX object CMakeFiles/astc-encoder.dir/third_party/astc-encoder/Source/astc_image_load_store.cpp.o
FAILED: CMakeFiles/astc-encoder.dir/third_party/astc-encoder/Source/astc_image_load_store.cpp.o 
/usr/bin/c++   -DTARGET_OS_LINUX -I/home/akruegersen/go/src/github.com/google/gapid -I/home/akruegersen/go/src/github.com/google/gapid/third_party/SPIRV-Headers/include -I/home/akruegersen/go/src/github.com/google/gapid/third_party/SPIRV-Tools/include -I/home/akruegersen/go/src/github.com/google/gapid/third_party/SPIRV-Tools/source -I/home/akruegersen/go/src/github.com/google/gapid/third_party/SPIRV-Tools-Generated -I/home/akruegersen/go/src/github.com/google/gapid/third_party/glslang/OGLCompilersDLL -I/home/akruegersen/go/src/github.com/google/gapid/core/memory_tracker/cc -I/home/akruegersen/go/src/github.com/google/gapid/core/vulkan/cc/include -std=c++0x -O3 -DNDEBUG -fPIC   -DGAPID_VERSION_AND_BUILD=\"0.4.0:0:developer\" -Wno-c++11-narrowing -MD -MT CMakeFiles/astc-encoder.dir/third_party/astc-encoder/Source/astc_image_load_store.cpp.o -MF CMakeFiles/astc-encoder.dir/third_party/astc-encoder/Source/astc_image_load_store.cpp.o.d -o CMakeFiles/astc-encoder.dir/third_party/astc-encoder/Source/astc_image_load_store.cpp.o -c /home/akruegersen/go/src/github.com/google/gapid/third_party/astc-encoder/Source/astc_image_load_store.cpp
In file included from /usr/include/c++/6/math.h:36:0,
                 from /home/akruegersen/go/src/github.com/google/gapid/third_party/astc-encoder/Source/astc_image_load_store.cpp:21:
/usr/include/c++/6/cmath: In function ‘constexpr float std::fmax(float, float)’:
/usr/include/c++/6/cmath:1452:28: error: ‘constexpr float std::fmax(float, float)’ conflicts with a previous declaration
   fmax(float __x, float __y)
                            ^
In file included from /home/akruegersen/go/src/github.com/google/gapid/third_party/astc-encoder/Source/astc_codec_internals.h:22:0,
                 from /home/akruegersen/go/src/github.com/google/gapid/third_party/astc-encoder/Source/astc_image_load_store.cpp:16:
/home/akruegersen/go/src/github.com/google/gapid/third_party/astc-encoder/Source/mathlib.h:30:7: note: previous declaration ‘float fmax(float, float)’
 float fmax(float p, float q);
       ^~~~
In file included from /usr/include/c++/6/math.h:36:0,
                 from /home/akruegersen/go/src/github.com/google/gapid/third_party/astc-encoder/Source/astc_image_load_store.cpp:21:
/usr/include/c++/6/cmath: In function ‘constexpr float std::fmin(float, float)’:
/usr/include/c++/6/cmath:1472:28: error: ‘constexpr float std::fmin(float, float)’ conflicts with a previous declaration
   fmin(float __x, float __y)
                            ^
In file included from /home/akruegersen/go/src/github.com/google/gapid/third_party/astc-encoder/Source/astc_codec_internals.h:22:0,
                 from /home/akruegersen/go/src/github.com/google/gapid/third_party/astc-encoder/Source/astc_image_load_store.cpp:16:
/home/akruegersen/go/src/github.com/google/gapid/third_party/astc-encoder/Source/mathlib.h:31:7: note: previous declaration ‘float fmin(float, float)’
 float fmin(float p, float q);
       ^~~~
In file included from /home/akruegersen/go/src/github.com/google/gapid/third_party/astc-encoder/Source/astc_image_load_store.cpp:21:0:
/usr/include/c++/6/math.h: At global scope:
/usr/include/c++/6/math.h:89:12: error: ‘constexpr float std::fmax(float, float)’ conflicts with a previous declaration
 using std::fmax;
            ^~~~
In file included from /home/akruegersen/go/src/github.com/google/gapid/third_party/astc-encoder/Source/astc_codec_internals.h:22:0,
                 from /home/akruegersen/go/src/github.com/google/gapid/third_party/astc-encoder/Source/astc_image_load_store.cpp:16:
/home/akruegersen/go/src/github.com/google/gapid/third_party/astc-encoder/Source/mathlib.h:30:7: note: previous declaration ‘float fmax(float, float)’
 float fmax(float p, float q);
       ^~~~
In file included from /home/akruegersen/go/src/github.com/google/gapid/third_party/astc-encoder/Source/astc_image_load_store.cpp:21:0:
/usr/include/c++/6/math.h:90:12: error: ‘constexpr float std::fmin(float, float)’ conflicts with a previous declaration
 using std::fmin;
            ^~~~
In file included from /home/akruegersen/go/src/github.com/google/gapid/third_party/astc-encoder/Source/astc_codec_internals.h:22:0,
                 from /home/akruegersen/go/src/github.com/google/gapid/third_party/astc-encoder/Source/astc_image_load_store.cpp:16:
/home/akruegersen/go/src/github.com/google/gapid/third_party/astc-encoder/Source/mathlib.h:31:7: note: previous declaration ‘float fmin(float, float)’
 float fmin(float p, float q);
       ^~~~
cc1plus: warning: unrecognized command line option ‘-Wno-c++11-narrowing’
[14/561] Building CXX object CMakeFiles/astc-encoder.dir/third_party/astc-encoder/Source/astc_decompress_symbolic.cpp.o
FAILED: CMakeFiles/astc-encoder.dir/third_party/astc-encoder/Source/astc_decompress_symbolic.cpp.o 
/usr/bin/c++   -DTARGET_OS_LINUX -I/home/akruegersen/go/src/github.com/google/gapid -I/home/akruegersen/go/src/github.com/google/gapid/third_party/SPIRV-Headers/include -I/home/akruegersen/go/src/github.com/google/gapid/third_party/SPIRV-Tools/include -I/home/akruegersen/go/src/github.com/google/gapid/third_party/SPIRV-Tools/source -I/home/akruegersen/go/src/github.com/google/gapid/third_party/SPIRV-Tools-Generated -I/home/akruegersen/go/src/github.com/google/gapid/third_party/glslang/OGLCompilersDLL -I/home/akruegersen/go/src/github.com/google/gapid/core/memory_tracker/cc -I/home/akruegersen/go/src/github.com/google/gapid/core/vulkan/cc/include -std=c++0x -O3 -DNDEBUG -fPIC   -DGAPID_VERSION_AND_BUILD=\"0.4.0:0:developer\" -Wno-c++11-narrowing -MD -MT CMakeFiles/astc-encoder.dir/third_party/astc-encoder/Source/astc_decompress_symbolic.cpp.o -MF CMakeFiles/astc-encoder.dir/third_party/astc-encoder/Source/astc_decompress_symbolic.cpp.o.d -o CMakeFiles/astc-encoder.dir/third_party/astc-encoder/Source/astc_decompress_symbolic.cpp.o -c /home/akruegersen/go/src/github.com/google/gapid/third_party/astc-encoder/Source/astc_decompress_symbolic.cpp
In file included from /usr/include/c++/6/math.h:36:0,
                 from /home/akruegersen/go/src/github.com/google/gapid/third_party/astc-encoder/Source/astc_decompress_symbolic.cpp:20:
/usr/include/c++/6/cmath: In function ‘constexpr float std::fmax(float, float)’:
/usr/include/c++/6/cmath:1452:28: error: ‘constexpr float std::fmax(float, float)’ conflicts with a previous declaration
   fmax(float __x, float __y)
                            ^
In file included from /home/akruegersen/go/src/github.com/google/gapid/third_party/astc-encoder/Source/astc_codec_internals.h:22:0,
                 from /home/akruegersen/go/src/github.com/google/gapid/third_party/astc-encoder/Source/astc_decompress_symbolic.cpp:17:
/home/akruegersen/go/src/github.com/google/gapid/third_party/astc-encoder/Source/mathlib.h:30:7: note: previous declaration ‘float fmax(float, float)’
 float fmax(float p, float q);
       ^~~~
In file included from /usr/include/c++/6/math.h:36:0,
                 from /home/akruegersen/go/src/github.com/google/gapid/third_party/astc-encoder/Source/astc_decompress_symbolic.cpp:20:
/usr/include/c++/6/cmath: In function ‘constexpr float std::fmin(float, float)’:
/usr/include/c++/6/cmath:1472:28: error: ‘constexpr float std::fmin(float, float)’ conflicts with a previous declaration
   fmin(float __x, float __y)
                            ^
In file included from /home/akruegersen/go/src/github.com/google/gapid/third_party/astc-encoder/Source/astc_codec_internals.h:22:0,
                 from /home/akruegersen/go/src/github.com/google/gapid/third_party/astc-encoder/Source/astc_decompress_symbolic.cpp:17:
/home/akruegersen/go/src/github.com/google/gapid/third_party/astc-encoder/Source/mathlib.h:31:7: note: previous declaration ‘float fmin(float, float)’
 float fmin(float p, float q);
       ^~~~
In file included from /home/akruegersen/go/src/github.com/google/gapid/third_party/astc-encoder/Source/astc_decompress_symbolic.cpp:20:0:
/usr/include/c++/6/math.h: At global scope:
/usr/include/c++/6/math.h:89:12: error: ‘constexpr float std::fmax(float, float)’ conflicts with a previous declaration
 using std::fmax;
            ^~~~
In file included from /home/akruegersen/go/src/github.com/google/gapid/third_party/astc-encoder/Source/astc_codec_internals.h:22:0,
                 from /home/akruegersen/go/src/github.com/google/gapid/third_party/astc-encoder/Source/astc_decompress_symbolic.cpp:17:
/home/akruegersen/go/src/github.com/google/gapid/third_party/astc-encoder/Source/mathlib.h:30:7: note: previous declaration ‘float fmax(float, float)’
 float fmax(float p, float q);
       ^~~~
In file included from /home/akruegersen/go/src/github.com/google/gapid/third_party/astc-encoder/Source/astc_decompress_symbolic.cpp:20:0:
/usr/include/c++/6/math.h:90:12: error: ‘constexpr float std::fmin(float, float)’ conflicts with a previous declaration
 using std::fmin;
            ^~~~
In file included from /home/akruegersen/go/src/github.com/google/gapid/third_party/astc-encoder/Source/astc_codec_internals.h:22:0,
                 from /home/akruegersen/go/src/github.com/google/gapid/third_party/astc-encoder/Source/astc_decompress_symbolic.cpp:17:
/home/akruegersen/go/src/github.com/google/gapid/third_party/astc-encoder/Source/mathlib.h:31:7: note: previous declaration ‘float fmin(float, float)’
 float fmin(float p, float q);
       ^~~~
cc1plus: warning: unrecognized command line option ‘-Wno-c++11-narrowing’
[15/561] Building CXX object CMakeFiles/astc-encoder.dir/third_party/astc-encoder/Source/astc_symbolic_physical.cpp.o
ninja: build stopped: subcommand failed.
Error running /usr/bin/ninja [install]: Process returned error
   Cause: exit status 1
exit status 1```

**Comment by AWoloszyn** [comment]
It looks like this is an issue with astc-encoder  and gcc 6.3.

Both define fmin and friends. I am not sure why this works on 4.8, but I would guess it has to do with what goes in which namespace by default.

I have opened #636 to investigate this futher.

In the mean-time you can either drop to a lower version of GCC (4.8 is well tested) or remove fmin/fmax from the astc library. IT does not look like they are being used anywhere anyway.

**Comment by Wyverex42** [comment]
Note that on gcc 6.3 (and also 5.4 for that matter), even after removing fmin/fmax from astc, there is still this error, which was just a warning on gcc 4.8:

```[2/556] Building CXX object CMakeFiles/astc-encoder.dir/third_party/astc-encoder/Source/softfloat.cpp.o
FAILED: CMakeFiles/astc-encoder.dir/third_party/astc-encoder/Source/softfloat.cpp.o 
/usr/bin/c++   -DTARGET_OS_LINUX -I/home/akruegersen/go/src/github.com/google/gapid -I/home/akruegersen/go/src/github.com/google/gapid/third_party/SPIRV-Headers/include -I/home/akruegersen/go/src/github.com/google/gapid/third_party/SPIRV-Tools/include -I/home/akruegersen/go/src/github.com/google/gapid/third_party/SPIRV-Tools/source -I/home/akruegersen/go/src/github.com/google/gapid/third_party/SPIRV-Tools-Generated -I/home/akruegersen/go/src/github.com/google/gapid/third_party/glslang/OGLCompilersDLL -I/home/akruegersen/go/src/github.com/google/gapid/core/memory_tracker/cc -I/home/akruegersen/go/src/github.com/google/gapid/core/vulkan/cc/include -std=c++0x -O3 -DNDEBUG -fPIC   -DGAPID_VERSION_AND_BUILD=\"0.4.0:0:developer\" -Wno-c++11-narrowing -MD -MT CMakeFiles/astc-encoder.dir/third_party/astc-encoder/Source/softfloat.cpp.o -MF CMakeFiles/astc-encoder.dir/third_party/astc-encoder/Source/softfloat.cpp.o.d -o CMakeFiles/astc-encoder.dir/third_party/astc-encoder/Source/softfloat.cpp.o -c /home/akruegersen/go/src/github.com/google/gapid/third_party/astc-encoder/Source/softfloat.cpp
/home/akruegersen/go/src/github.com/google/gapid/third_party/astc-encoder/Source/softfloat.cpp: In function ‘sf32 sf16_to_sf32(sf16)’:
/home/akruegersen/go/src/github.com/google/gapid/third_party/astc-encoder/Source/softfloat.cpp:142:2: error: narrowing conversion of ‘2147483648u’ from ‘unsigned int’ to ‘int32_t {aka int}’ inside { } [-Wnarrowing]
  };
  ^
/home/akruegersen/go/src/github.com/google/gapid/third_party/astc-encoder/Source/softfloat.cpp:142:2: error: narrowing conversion of ‘2147713024u’ from ‘unsigned int’ to ‘int32_t {aka int}’ inside { } [-Wnarrowing]
/home/akruegersen/go/src/github.com/google/gapid/third_party/astc-encoder/Source/softfloat.cpp:142:2: error: narrowing conversion of ‘2147713024u’ from ‘unsigned int’ to ‘int32_t {aka int}’ inside { } [-Wnarrowing]
/home/akruegersen/go/src/github.com/google/gapid/third_party/astc-encoder/Source/softfloat.cpp:142:2: error: narrowing conversion of ‘2147942400u’ from ‘unsigned int’ to ‘int32_t {aka int}’ inside { } [-Wnarrowing]
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-c++11-narrowing’
[11/556] Building CXX object CMakeFiles/astc-encoder.dir/third_party/astc-encoder/Source/astc_image_load_store.cpp.o
ninja: build stopped: subcommand failed.
Error running /usr/bin/ninja [install]: Process returned error
   Cause: exit status 1
exit status 1
```

**Comment by ben-clayton** [comment]
Using #636 to track this.

**Comment by DanOlivier** [comment]
Changing `-Wno-c++11-narrowing` for just `-Wno-narrowing` (in `third_party/astc-encoder.cmake`) works for me...
